const FETCH_CAR = "FETCH_CAR";
const GET_CAR_DETAIL = "GET_CAR_DETAIL";
const SHOW_DETAIL = "SHOW_DETAIL";
const CAR_DATA_FILTERED = "CAR_DATA_FILTERED";

export { FETCH_CAR, GET_CAR_DETAIL, SHOW_DETAIL, CAR_DATA_FILTERED };
